server:
  port: 8080
  servlet:
    context-path: /viena-service
spring:
  datasource:
    url: jdbc:sqlserver://viena-map.database.windows.net:1433;databaseName=VienaDatabase
    username: adminISI
    password: '!passw0rd'
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: false
      maximum-pool-size: 50
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    database: SQL_SERVER
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_second_level_cache: false
      hibernate.enable_lazy_load_no_trans: true
      hibernate.show_sql: true
      hibernate.format_sql: true
  jta:
    enabled: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration




# Actuator Properties
management:
  endpoints:
    web:
      exposure:
        include:
        - loggers
        - health
        - info
        - metrics
        - env
  endpoint:
    env:
      enabled: true
    loggers:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true